# Simple workflow for deploying static content to GitHub Pages
name: Deploy blog files to repo

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true # Checkout private submodules(themes or something else).

      - name: Setup npm
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          npm install --force --verbose
          npm list

      - name: Configuration and patch
        run: |
          cp -r patch/modules/* node_modules/

      - name: List node modules
        run: tree -L 1 node_modules

      - name: Install Hexo
        run: npm install -g hexo-cli

      - name: Check Hexo version
        run: |
          node -v
          npm -v
          hexo -v

      - name: Setup git
        run: |
          git config --global init.defaultBranch main
          git config --global user.name "Muhan Li"
          git config --global user.email "limuhan@msn.com"

      - name: Setup git credentials
        env:
          PAT_TOKEN: ${{ secrets.TOKEN }}
        run: |
          GIT_URL="https://$PAT_TOKEN@github.com/muhac/blog.git"
          git clone $GIT_URL .deploy_git
          sed -i "s|PH_GIT_URL|${GIT_URL}|g" _config.yml

      - name: Setup deploy URL
        run: |
          WEB_URL=$(cat source/CNAME)
          sed -i "s|PH_WEB_URL|${WEB_URL}|g" _config.yml
          sed -i "s|PH_WEB_URL|${WEB_URL}|g" source/robots.txt

      - name: Build static content
        run: hexo generate

      - name: Publish to Pages
        run: hexo deploy

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Debug blog site
        uses: actions/upload-artifact@v4
        with:
          name: blog-site
          path: './public'

      - name: Debug node modules
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules
